---
- name: Manage Applications on Ravello
  connection: local
  hosts: all
  gather_facts: no
  roles:
    - ravello.lib
    - ravello.applications_create

  pre_tasks:
    - include_vars: app_list.yaml
      tags: [ always ]
